eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8100
spring:
  application:
    name: service-user
  datasource:
      url: jdbc:mysql://localhost:3306/oauth_db?useUnicode=true&characterEncoding=UTF-8&useSSL=true
      username: root
      password: 1qaz2wsx
      driverClassName: com.mysql.jdbc.Driver
  jpa:
      database: MYSQL
      showSql: true
      hibernate:
        namingStrategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect