eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8100
spring:
  application:
    name: service-user
  datasource:
      url: jdbc:mysql://localhost:3306/oauth_db?useUnicode=true&characterEncoding=UTF-8&useSSL=true
      username: root
      password: 1qaz2wsx
      driverClassName: com.mysql.jdbc.Driver
  jpa:
      database: MYSQL
      showSql: true
      hibernate:
        namingStrategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    database: 0
    host: 172.16.0.199
    port: 6379
#    password:
    pool:
      max-active: -1
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 5000
#自定义数据
self:
  data:
    redis:
      code:
        expire: 600
      access_token:
        expire: 7200
      refresh_token:
        expire: 15552000
    openid_session_attribute: OPENID
    xxtea_key: $@qaz()*